const Worklists = [
    {
    id: 1,
    title:"Create blog using PHP and MYSQL database with custom CMS.",
    image:"/images/news cms.png",
    url:"https://github.com/souravwebart/Create-blog-using-PHP-and-MYSQL-database-with-custom-CMS",
},
{
    id: 2,
    title:"Doctor Frontend dashboard using HTML and CSS",
    image:"/images/doctordashboard.PNG",
    url:"https://doctorappsourav.netlify.app/",
},
{
    id: 3,
    title:"Pizza Order Website using Node.Js and MongoDB (Partialy Completed)",
    image:"/images/pizza2.png",
    url:"https://github.com/souravwebart/Pizza-Order-Website-using-Node.Js-and-MongoDB",
},
{
    id: 4,
    title:"Scale-Capital Project using wordpress",
    image:"/images/scalecapital.png",
    url:"https://scalecapital.com/",
},
{
    id: 5,
    title:"Estimators Online Project using Wordpress",
    image:"/images/estimatorsproject.PNG",
    url:"https://dmsonpl.co.in/estimators-online/",
},
{
    id: 6,
    title:"Autharanticate in php",
    image:"/images/loginregister.png",
    url:"https://github.com/souravwebart/autharanticate-in-php",
},
{
    id: 7,
    title:"PHP-CRUD-Operations-with-MySql",
    image:"/images/crud.png",
    url:"https://github.com/souravwebart/PHP-CRUD-Operations-with-MySql",
},
{
    id: 8,
    title:"Visulization Dashboard using React and mongodb",
    image:"/images/reactdashboard.png",
    url:"https://github.com/souravwebart/visulization-Dashboard-using-react-and-MongoDB",
},
{
    id: 9,
    title:"Single Responsive page using HTML,CSS and REACT",
    image:"/images/singlereactpage.png",
    url:"https://github.com/souravwebart/single-responsive-page-using-HTML-CSS-and-react",
},
{
    id: 10,
    title:"Simple Contact Page using HTML and CSS",
    image:"/images/contactformhtmlandcss.png",
    url:"https://souravwebart.github.io/Simple-contact-page-in-HTML-and-CSS/",
},
{
    id: 11,
    title:"Asia Country API using React",
    image:"/images/countryapi.png",
    url:"https://github.com/souravwebart/Country-API",
},
{
    id: 12,
    title:"Single Page Digital Marketing Service Website (Frontend and Backend)",
    image:"/images/topdigitalbranding.png",
    url:"https://topdigitalbranding.com/",
},
{
    id: 13,
    title:"Simple Project work for C.R.I Fluid System in React",
    image:"/images/cri.png",
    url:"https://simplepageinreact.netlify.app/",
},
{
    id: 14,
    title:"Simple Page for YBOX Media in Wordpress",
    image:"/images/ybox.png",
    url:"https://dmsonpl.co.in/project12/",
},
{
    id: 15,
    title:"Landing page create for Webshark in HTML and CSS",
    image:"/images/webshark.png",
    url:"https://souravwebart.github.io/Project-work-for-webshark/",
},
{
    id: 15,
    title:"Create site for Aartisto Technologies pvt lts using wordpress",
    image:"/images/videoaartisto.png",
    url:"https://aartisto.com/best-video-marketing-services-in-india/",
},
{
   id: 16,
   title:"Attendence Dashboard Frontent project using React",
   image:"/images/attendence.png",
   url:"https://attendencedashboardsourav.netlify.app/",
},
{
    id: 17,
    title:"Insert Data using serialize method PHP Ajax",
    image:"/images/php ajax form.JPG",
    url:"https://github.com/souravwebart/Insert-Data-using-serialize-method-PHP-Ajax",

},
{
    id: 18,
    title:"Create X1-Race League Website using Wordpress",
    image:"/images/x1race.png",
    url:"https://dmsonpl.co.in/project13/",
},
{
    id: 19,
    title:"Create Free seo Copy digital Marketing Landing Page using Wordpress",
    image:"/images/freeseocopy.png",
    url:"https://dmsonpl.co.in/project14/",
},
{
    id: 20,
    title:"Create news website using Wordpress",
    image:"/images/news.png",
    url:"https://dmsonpl.co.in/project15/",
},
{
    id: 21,
    title:"Dawat restaurant project using HTML, CSS, and javascript",
    image:"/images/dawat resturant.png",
    url:"https://dawatresturantbysourav.netlify.app/",
},
{
    id: 22,
    title:"Simple Employee Login and Dashboard (Frontend)",
    image:"/images/simple-employee-login.png",
    url:"https://employeelogindashboard.netlify.app/",
},
{
    id: 23,
    title:"Simple Blog API Website using React",
    image:"/images/newsblogreact.png",
    url:"https://blognewssourav.netlify.app/",
},
{
    id: 24,
    title:"Simple GitHub Repo using API and React",
    image:"/images/c.png",
    url:"https://githubjohnpapabysourav.netlify.app/",
},
{
    id: 25,
    title:"united1 Project using Wordpress",
    image:"/images/united1.png",
    url:"https://united1.andhrasite.com/",
},
{
    id: 26,
    title:"Indrayani farms Project using Wordpress",
    image:"/images/ikf.png",
    url:"http://indrayanifarms.andhrasite.com/",
},
{
    id: 27,
    title:"word tags input project in React",
    image:"/images/wtu.png",
    url:"https://word-tags-input.netlify.app/",
},
{
    id: 28,
    title:"Dazyit Project using Html, CSS, and JS",
    image:"/images/dazyit.png",
    url:"https://dazyit.netlify.app/",
},
{
    id: 29,
    title:"Ajax POST request with jQuery and PHP",
    image:"/images/Ajax POST request.JPG",
    url:"https://github.com/souravwebart/Ajax-POST-request-with-jQuery-and-PHP",
},
{
    id: 30,
    title:"FAQ in Html and css",
    image:"/images/faq.PNG",
    url:"https://github.com/souravwebart/faq-in-html-css",
},

]
export default Worklists;