
const EducationTrainingLists = [
    {
      id: 1,
      name: "AGARTALA GAS TURBINE (AGTCCPP NEEPCO LTD) [ETRWTC000010]",
      imgURL:"./images/neepco.png",
      title:"Civil Engineer",
      text: "I have learned many things theoretically as well as practically, civil structures of a thermal power plant, the duty of a civil engineer in the field of necessary civil construction works and maintenance works of a power plant.",
      year:"2019-2021",
    },
    {
        id: 2,
        name: "Oil and Natural gas Corporation Limited ",
        imgURL:"./images/ongc.png",
        title:"Project work on water treatment plant in ONGC",
        text: "I had successfully completed my Project work on a water treatment plant in ONGC in a discipline of BE Civil Engineering second year,",
        year:"January 2016 — February 2016",
      },
      {
        id: 3,
        name: "Govt. of Tripura public work Department (PWD)",
        imgURL:"./images/pwd.jpg",
        title:"Trainee",
        text: "I had successfully completed my Vocational practical training under the Government of Tripura office of the executive Engineer Agartala division No.1, PWD (R&B) Agartala, Tripura in presence of office order no 7.6 (25) -PWD (GE)/2014/ (S - 7)/7486 - 537.",
        year:"July 2016 — Auguest 2016",
      },
      {
        id: 4,
        name: "Twenty19.com",
        imgURL:"./images/twenty19.png",
        title:"Campus Ambassador",
        text: "I had successfully completed the Twenty19 campus ambassador program between December 2016 and June 2017.",
        year:"December 2016 — June 2017 ",
      },
      {
        id: 5,
        name: "Nearbuy.com Incorporated in May 2010 as Groupon India Private Limited ",
        imgURL:"./images/nearbuy.PNG",
        title:"Digital Marketing",
        text: "I had successfully completed the Nearbuy campus ambassador program in Digital Marketing between November 2016 to December 2016",
        year:"November 2016 — December 2016",
      },
      {
        id: 6,
        name: "TruckPaPa E-commerce Pvt.Ltd",
        imgURL:"./images/truckpapa.jpg",
        title:"Social media marketing",
        text: "I had successfully completed the Social media marketing Internship from November 2016 to January 2017.",
        year:"November 2016 — January 2017",
      },
      {
        id: 7,
        name: "Junglidonkey.com",
        imgURL:"./images/junglidonkey.png",
        title:"Social Media Marketing & Graphic Designing internship",
        text: "I had successfully completed the Social Media Marketing & Graphic Designing internship from January 2017 to February 2017.",
        year:"January 2017 — February 2017",
      },
      {
        id: 8,
        name: "Dailymyshopping Online Service Pvt.Ltd",
        imgURL:"./images/dailymyshopping.jpg",
        title:"Wordpress Development and SEO",
        text: "I had successfully completed the Wordpress Development and SEO full-time project work from December 2018 to December 2019.",
        year:"December 2018 to December 2019",
      },
      {
        id: 9,
        name: "Artisto Technologies Private Limited.",
        imgURL:"./images/aartisto.png",
        title:"Web Development",
        text: "I had successfully completed the Web Development full-time Internship.",
        year:"August 2021 - December 2021",
      },
      {
        id: 10,
        name: "Thumbstack Technologies.",
        imgURL:"./images/thumbstack.png",
        title:"HTML Developer",
        text: "I had successfully completed the full-time Html Development Internship.",
        year:"September 2021 - December 2021",
      },
      {
        id: 11,
        name: "Thumbstack Technologies.",
        imgURL:"./images/thumbstack.png",
        title:"FrontEnd Developer",
        text: "Currently Working as a FrontEnd Developer (Full-Time).",
        year:"January 2022",
      },
  ];
  
  export default EducationTrainingLists;